default:
  # This variable is overridden in the repository CI settings
  # Remove that override once System Team updates the
  # JS_BUILD_IMAGE at the groupwide SKAO level.
  # ~ bjmc, September 2026
  image: ${JS_BUILD_IMAGE}

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  a11y_urls: $CAR_NPM_REPOSITORY_URL

stages:
  - lint
  - build
  - test
  - pages
  - deploy
  - accessibility
  - scan
  - publish

# list the current top level dependencies for the project
list_dependencies:
  stage: test
  tags:
    - ${SKA_K8S_RUNNER}
  before_script:
    - corepack enable
    - make js-install
  script:
    - npm list --depth=0 --json >> npm_deps.json
    - npm list --depth=0  >> npm_deps.txt
    - mkdir .public
    - cp npm_deps.txt .public/
    - cp npm_deps.json .public/
  artifacts:
    paths:
      - .public

# Build the application
build:
  stage: build
  tags:
    - ${SKA_K8S_RUNNER}
  before_script:
    - corepack enable
    - make js-install
  script:
    - yarn build

# Roll up the application
distribution:
  stage: build
  tags:
    - ${SKA_K8S_RUNNER}
  before_script:
    - corepack enable
    - make js-install
  script:
    - yarn build
  artifacts:
    paths:
      - dist/

# Publish the artifacts to CAR
publish-to-car:
  stage: publish
  image: artefact.skao.int/ska-node-ubuntu26:1.0.2
  tags:
    - ${SKA_K8S_RUNNER}
  before_script:
    - npm config set registry $CAR_NPM_REPOSITORY_URL
    # npm config set always-auth true
    - echo $CAR_NPM_REPOSITORY_URL | awk -F '://' '{ cmd="npm config set -- //"$2":_auth \"${CAR_NPM_TOKEN}\" ";system(cmd) }'
    - npm config get
  script:
    - npm publish
  rules:
    # Publish from a tag for a release
    - if: $CI_COMMIT_TAG

# Publish the artifacts to gitlab registry
publish-to-gitlab:
  image: artefact.skao.int/ska-node-ubuntu26:1.0.2
  stage: publish
  tags:
    - ${SKA_K8S_RUNNER}
  before_script:
    - npm config set @ska-telescope:registry https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/
    - npm config set -- '//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken' "${CI_JOB_TOKEN}"
  script:
    - npm version --no-git-tag-version $(npm show latest version)-dev.$CI_COMMIT_SHORT_SHA
    - npm publish
  rules:
    # Do not publish on a tag pipeline, note this shouldn't transfer over to SKAO templates
    - if: $CI_COMMIT_TAG
      when: never

# export the report
pages:
  stage: pages
  tags:
    - ${SKA_K8S_RUNNER}
  dependencies:
    - js-test
    - list_dependencies
    - code_quality
  before_script: []
  script:
    - mv public/* .
    - cp -r build/* public
    - cp -r .public/* public
  artifacts:
    paths:
      - public
    expire_in: 30 days

docs-build:
  image: artefact.skao.int/ska-build-python-ubuntu26:1.0.2
  variables:
    PIP_BREAK_SYSTEM_PACKAGES: "1"

include:
  - template: Code-Quality.gitlab-ci.yml
  - template: "Verify/Accessibility.gitlab-ci.yml"

  # Javascript packages lint, test and audit
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/js.gitlab-ci.yml'

  # documentation pages pipeline
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/docs.gitlab-ci.yml'

  # .post step finalizers eg: badges
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/finaliser.gitlab-ci.yml'
  # deploy
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/release.gitlab-ci.yml'

code_quality:
  # https://docs.gitlab.com/ee/user/project/merge_requests/code_quality.html#generate-an-html-report
  artifacts:
    paths: [gl-code-quality-report.json]
  # disable dind service as it's not needed for ${SKA_K8S_RUNNER} runners
  script: echo 'code quality does not need a script'
  services: []
  tags:
    - ${SKA_K8S_RUNNER}
  # We need to merge the rules with what we have here on template rules
  # https://gitlab.com/ska-telescope/templates-repository/-/blob/master/gitlab-ci/includes/rules.gitlab-ci.yml
  # https://docs.gitlab.com/ee/user/project/merge_requests/code_quality.html#using-with-merge-request-pipelines
  rules:
    - if: '$CODE_QUALITY_DISABLED'
      when: never
    # don't run branch pipeline if there are open MRs
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push"
      when: never
    # run on MRs
    - if: $CI_MERGE_REQUEST_IID
    # For `$CI_DEFAULT_BRANCH` branch, create a pipeline (this includes on schedules, pushes, merges, etc.).
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    # For tags, create a pipeline.
    - if: '$CI_COMMIT_TAG'
    # run on branches
    - if: '$CI_COMMIT_BRANCH'
