nodeLinker: node-modules

npmScopes:
  ska-telescope:
    npmRegistryServer: "https://artefact.skao.int/repository/npm-internal/"

packageExtensions:
  "storybook@*":
    peerDependencies:
      react: "*"
