// Primary and Secondary Palettes
export const DARK_PRIMARY = {
  light: '#484848',
  main: '#212121',
  dark: '#888888',
  contrastText: '#FFFFFF',
};

export const DARK_SECONDARY = {
  light: '#FFF04E',
  main: '#F7BE00',
  dark: '#BF8E00',
  contrastText: '#000000',
};

export const LIGHT_PRIMARY = {
  light: '#C1C6CA',
  main: '#F4F9FD',
  dark: '#919599',
  contrastText: '#000000',
};

export const LIGHT_SECONDARY = {
  light: '#472A97',
  main: '#070068',
  dark: '#00003D',
  contrastText: '#FFFFFF',
};

// Status Colors
export const SUCCESS = {
  bg: '#FFFFFF',
  fg: '#388E3C',
  full: ['#6ABF69', '#388E3C', '#00600F', '#000000', '#FFFFFF', '#FFFFFF'],
};

export const ERROR_1 = {
  bg: '#FFFFFF',
  fg: '#C62828',
  full: ['#FF5F52', '#C62828', '#8A0000', '#000000', '#FFFFFF', '#FFFFFF'],
};

export const ERROR_2 = {
  bg: '#000000',
  fg: '#FDD835',
  full: ['#FFFF6B', '#FDD835', '#C6A700', '#000000', '#000000', '#000000'],
};

export const ERROR_3 = {
  bg: '#FFFFFF',
  fg: '#FB8C00',
  full: ['#FFBD45', '#FB8C00', '#C25E00', '#000000', '#FFFFFF', '#000000'],
};

export const ERROR_4 = {
  bg: '#000000',
  fg: '#B3D4FF',
  full: [
    '#B3D4FF', // soft blue
    '#5B9BD5', // medium blue
    '#1E4E79', // deep blue
    '#FFFFFF', // white for contrast
    '#0A0A0A', // background anchor
    '#FFFFFF', // repeated white for balance
  ],
};

export const ERROR_5 = {
  bg: '#FFFFFF',
  fg: '#000000',
  full: ['#FFFFFF', '#000000', '#C2C2C2', '#000000', '#FFFFFF', '#000000'],
};

export const SOFT_SUCCESS = {
  bg: '#d4e9dc',
  fg: '#2e7d32',
  full: ['#d4e9dc', '#a8d4b8', '#7bbf94', '#4e9c76', '#2e7d32', '#ffffff'],
};

export const SOFT_ERROR_1 = {
  bg: '#f8d7da',
  fg: '#ad1f1f',
  full: ['#f8d7da', '#f29ca0', '#e57373', '#d32f2f', '#ad1f1f', '#ffffff'],
};

export const SOFT_ERROR_2 = {
  bg: '#fffbe6',
  fg: '#8a6d3b',
  full: ['#fffbe6', '#fff2b3', '#ffe680', '#ffd24d', '#8a6d3b', '#000000'],
};

export const SOFT_ERROR_3 = {
  bg: '#ffe5b4',
  fg: '#c25e00',
  full: ['#ffe5b4', '#ffc47c', '#ff9800', '#f57c00', '#c25e00', '#000000'],
};

export const SOFT_ERROR_4 = {
  bg: '#e1f0fb',
  fg: '#1565c0',
  full: ['#e1f0fb', '#a8d4f2', '#7bb8e8', '#4a90d9', '#1565c0', '#ffffff'],
};

export const SOFT_ERROR_5 = {
  bg: '#FFFFFF',
  fg: '#000000',
  full: ['#FFFFFF', '#FFFFFF', '#C2C2C2', '#000000', '#000000', '#000000'],
};

// Logo Colors
export const SKAO_LOGO = {
  primary: '#070068',
  accent: '#E70068',
  light: '#FFFFFF',
};

export const SKAO_TELESCOPE = {
  1: '#9B6017',
  2: '#F7BE00',
  mid: '#9B6017',
  low: '#F7BE00',
};

export const PROTANOPIA_PRIMARY_LIGHT = {
  light: '#A0A0FF',
  main: '#6060FF',
  dark: '#3030AA',
  contrastText: '#FFFFFF',
};
export const PROTANOPIA_PRIMARY_DARK = {
  light: '#8080CC',
  main: '#4040AA',
  dark: '#202060',
  contrastText: '#FFFFFF',
};
export const PROTANOPIA_SECONDARY_LIGHT = {
  light: '#FFD580',
  main: '#FFB347',
  dark: '#CC8400',
  contrastText: '#000000',
};
export const PROTANOPIA_SECONDARY_DARK = {
  light: '#CCAA66',
  main: '#AA8030',
  dark: '#804000',
  contrastText: '#000000',
};

export const PROTANOMALY_PRIMARY_LIGHT = {
  light: '#A0E0FF',
  main: '#60C0FF',
  dark: '#3080AA',
  contrastText: '#000000',
};
export const PROTANOMALY_PRIMARY_DARK = {
  light: '#80B0CC',
  main: '#4080AA',
  dark: '#205060',
  contrastText: '#FFFFFF',
};
export const PROTANOMALY_SECONDARY_LIGHT = {
  light: '#FFE0A0',
  main: '#FFC060',
  dark: '#AA8030',
  contrastText: '#000000',
};
export const PROTANOMALY_SECONDARY_DARK = {
  light: '#CCAA66',
  main: '#AA8030',
  dark: '#804000',
  contrastText: '#000000',
};

export const DEUTERANOPIA_PRIMARY_LIGHT = {
  light: '#A0A0FF',
  main: '#6060FF',
  dark: '#3030AA',
  contrastText: '#FFFFFF',
};
export const DEUTERANOPIA_PRIMARY_DARK = {
  light: '#8080CC',
  main: '#4040AA',
  dark: '#202060',
  contrastText: '#FFFFFF',
};
export const DEUTERANOPIA_SECONDARY_LIGHT = {
  light: '#FFD580',
  main: '#FFB347',
  dark: '#CC8400',
  contrastText: '#000000',
};
export const DEUTERANOPIA_SECONDARY_DARK = {
  light: '#CCAA66',
  main: '#AA8030',
  dark: '#804000',
  contrastText: '#000000',
};

export const DEUTERANOMALY_PRIMARY_LIGHT = {
  light: '#A0E0FF',
  main: '#60C0FF',
  dark: '#3080AA',
  contrastText: '#000000',
};
export const DEUTERANOMALY_PRIMARY_DARK = {
  light: '#80B0CC',
  main: '#4080AA',
  dark: '#205060',
  contrastText: '#FFFFFF',
};
export const DEUTERANOMALY_SECONDARY_LIGHT = {
  light: '#FFE0A0',
  main: '#FFC060',
  dark: '#AA8030',
  contrastText: '#000000',
};
export const DEUTERANOMALY_SECONDARY_DARK = {
  light: '#CCAA66',
  main: '#AA8030',
  dark: '#804000',
  contrastText: '#000000',
};

export const TRITANOPIA_PRIMARY_LIGHT = {
  light: '#FFCCCC',
  main: '#FF9999',
  dark: '#CC6666',
  contrastText: '#000000',
};
export const TRITANOPIA_PRIMARY_DARK = {
  light: '#CC9999',
  main: '#AA6666',
  dark: '#803333',
  contrastText: '#FFFFFF',
};
export const TRITANOPIA_SECONDARY_LIGHT = {
  light: '#CCCCFF',
  main: '#9999FF',
  dark: '#6666CC',
  contrastText: '#000000',
};
export const TRITANOPIA_SECONDARY_DARK = {
  light: '#9999CC',
  main: '#6666AA',
  dark: '#333380',
  contrastText: '#FFFFFF',
};

export const TRITANOMALY_PRIMARY_LIGHT = {
  light: '#FFB3B3',
  main: '#FF6666',
  dark: '#CC3333',
  contrastText: '#000000',
};
export const TRITANOMALY_PRIMARY_DARK = {
  light: '#CC9999',
  main: '#AA6666',
  dark: '#803333',
  contrastText: '#FFFFFF',
};
export const TRITANOMALY_SECONDARY_LIGHT = {
  light: '#B3FFB3',
  main: '#66FF66',
  dark: '#33CC33',
  contrastText: '#000000',
};
export const TRITANOMALY_SECONDARY_DARK = {
  light: '#99CC99',
  main: '#66AA66',
  dark: '#338033',
  contrastText: '#FFFFFF',
};

export const ACHROMATOMALY_PRIMARY_LIGHT = {
  light: '#CCCCCC',
  main: '#999999',
  dark: '#666666',
  contrastText: '#000000',
};
export const ACHROMATOMALY_PRIMARY_DARK = {
  light: '#AAAAAA',
  main: '#777777',
  dark: '#444444',
  contrastText: '#FFFFFF',
};
export const ACHROMATOMALY_SECONDARY_LIGHT = {
  light: '#EEEEEE',
  main: '#BBBBBB',
  dark: '#888888',
  contrastText: '#000000',
};
export const ACHROMATOMALY_SECONDARY_DARK = {
  light: '#CCCCCC',
  main: '#999999',
  dark: '#666666',
  contrastText: '#FFFFFF',
};

export const ACHROMATOPSIA_PRIMARY_LIGHT = {
  light: '#DDDDDD',
  main: '#AAAAAA',
  dark: '#555555',
  contrastText: '#000000',
};
export const ACHROMATOPSIA_PRIMARY_DARK = {
  light: '#BBBBBB',
  main: '#888888',
  dark: '#444444',
  contrastText: '#FFFFFF',
};
export const ACHROMATOPSIA_SECONDARY_LIGHT = {
  light: '#F0F0F0',
  main: '#C0C0C0',
  dark: '#707070',
  contrastText: '#000000',
};
export const ACHROMATOPSIA_SECONDARY_DARK = {
  light: '#D0D0D0',
  main: '#A0A0A0',
  dark: '#505050',
  contrastText: '#FFFFFF',
};

export const Colors = () => ({
  DARK_PRIMARY,
  DARK_PRIMARY_MAIN: DARK_PRIMARY.main,
  DARK_PRIMARY_LIGHT: DARK_PRIMARY.light,
  DARK_PRIMARY_DARK: DARK_PRIMARY.dark,
  DARK_PRIMARY_CONTRAST: DARK_PRIMARY.contrastText,
  DARK_SECONDARY,
  DARK_SECONDARY_MAIN: DARK_SECONDARY.main,
  DARK_SECONDARY_LIGHT: DARK_SECONDARY.light,
  DARK_SECONDARY_DARK: DARK_SECONDARY.dark,
  DARK_SECONDARY_CONTRAST: DARK_SECONDARY.contrastText,

  LIGHT_PRIMARY,
  LIGHT_PRIMARY_MAIN: LIGHT_PRIMARY.main,
  LIGHT_PRIMARY_LIGHT: LIGHT_PRIMARY.light,
  LIGHT_PRIMARY_DARK: LIGHT_PRIMARY.dark,
  LIGHT_PRIMARY_CONTRAST: LIGHT_PRIMARY.contrastText,
  LIGHT_SECONDARY,
  LIGHT_SECONDARY_MAIN: LIGHT_SECONDARY.main,
  LIGHT_SECONDARY_LIGHT: LIGHT_SECONDARY.light,
  LIGHT_SECONDARY_DARK: LIGHT_SECONDARY.dark,
  LIGHT_SECONDARY_CONTRAST: LIGHT_SECONDARY.contrastText,
  // PROTANOPIA
  PROTANOPIA_PRIMARY_LIGHT,
  PROTANOPIA_PRIMARY_LIGHT_MAIN: PROTANOPIA_PRIMARY_LIGHT.main,
  PROTANOPIA_PRIMARY_LIGHT_LIGHT: PROTANOPIA_PRIMARY_LIGHT.light,
  PROTANOPIA_PRIMARY_LIGHT_DARK: PROTANOPIA_PRIMARY_LIGHT.dark,
  PROTANOPIA_PRIMARY_LIGHT_CONTRAST: PROTANOPIA_PRIMARY_LIGHT.contrastText,

  PROTANOPIA_PRIMARY_DARK,
  PROTANOPIA_PRIMARY_DARK_MAIN: PROTANOPIA_PRIMARY_DARK.main,
  PROTANOPIA_PRIMARY_DARK_LIGHT: PROTANOPIA_PRIMARY_DARK.light,
  PROTANOPIA_PRIMARY_DARK_DARK: PROTANOPIA_PRIMARY_DARK.dark,
  PROTANOPIA_PRIMARY_DARK_CONTRAST: PROTANOPIA_PRIMARY_DARK.contrastText,

  PROTANOPIA_SECONDARY_LIGHT,
  PROTANOPIA_SECONDARY_LIGHT_MAIN: PROTANOPIA_SECONDARY_LIGHT.main,
  PROTANOPIA_SECONDARY_LIGHT_LIGHT: PROTANOPIA_SECONDARY_LIGHT.light,
  PROTANOPIA_SECONDARY_LIGHT_DARK: PROTANOPIA_SECONDARY_LIGHT.dark,
  PROTANOPIA_SECONDARY_LIGHT_CONTRAST: PROTANOPIA_SECONDARY_LIGHT.contrastText,

  PROTANOPIA_SECONDARY_DARK,
  PROTANOPIA_SECONDARY_DARK_MAIN: PROTANOPIA_SECONDARY_DARK.main,
  PROTANOPIA_SECONDARY_DARK_LIGHT: PROTANOPIA_SECONDARY_DARK.light,
  PROTANOPIA_SECONDARY_DARK_DARK: PROTANOPIA_SECONDARY_DARK.dark,
  PROTANOPIA_SECONDARY_DARK_CONTRAST: PROTANOPIA_SECONDARY_DARK.contrastText,

  // PROTANOMALY
  PROTANOMALY_PRIMARY_LIGHT,
  PROTANOMALY_PRIMARY_LIGHT_MAIN: PROTANOMALY_PRIMARY_LIGHT.main,
  PROTANOMALY_PRIMARY_LIGHT_LIGHT: PROTANOMALY_PRIMARY_LIGHT.light,
  PROTANOMALY_PRIMARY_LIGHT_DARK: PROTANOMALY_PRIMARY_LIGHT.dark,
  PROTANOMALY_PRIMARY_LIGHT_CONTRAST: PROTANOMALY_PRIMARY_LIGHT.contrastText,

  PROTANOMALY_PRIMARY_DARK,
  PROTANOMALY_PRIMARY_DARK_MAIN: PROTANOMALY_PRIMARY_DARK.main,
  PROTANOMALY_PRIMARY_DARK_LIGHT: PROTANOMALY_PRIMARY_DARK.light,
  PROTANOMALY_PRIMARY_DARK_DARK: PROTANOMALY_PRIMARY_DARK.dark,
  PROTANOMALY_PRIMARY_DARK_CONTRAST: PROTANOMALY_PRIMARY_DARK.contrastText,

  PROTANOMALY_SECONDARY_LIGHT,
  PROTANOMALY_SECONDARY_LIGHT_MAIN: PROTANOMALY_SECONDARY_LIGHT.main,
  PROTANOMALY_SECONDARY_LIGHT_LIGHT: PROTANOMALY_SECONDARY_LIGHT.light,
  PROTANOMALY_SECONDARY_LIGHT_DARK: PROTANOMALY_SECONDARY_LIGHT.dark,
  PROTANOMALY_SECONDARY_LIGHT_CONTRAST: PROTANOMALY_SECONDARY_LIGHT.contrastText,

  PROTANOMALY_SECONDARY_DARK,
  PROTANOMALY_SECONDARY_DARK_MAIN: PROTANOMALY_SECONDARY_DARK.main,
  PROTANOMALY_SECONDARY_DARK_LIGHT: PROTANOMALY_SECONDARY_DARK.light,
  PROTANOMALY_SECONDARY_DARK_DARK: PROTANOMALY_SECONDARY_DARK.dark,
  PROTANOMALY_SECONDARY_DARK_CONTRAST: PROTANOMALY_SECONDARY_DARK.contrastText,

  // DEUTERANOPIA
  DEUTERANOPIA_PRIMARY_LIGHT,
  DEUTERANOPIA_PRIMARY_LIGHT_MAIN: DEUTERANOPIA_PRIMARY_LIGHT.main,
  DEUTERANOPIA_PRIMARY_LIGHT_LIGHT: DEUTERANOPIA_PRIMARY_LIGHT.light,
  DEUTERANOPIA_PRIMARY_LIGHT_DARK: DEUTERANOPIA_PRIMARY_LIGHT.dark,
  DEUTERANOPIA_PRIMARY_LIGHT_CONTRAST: DEUTERANOPIA_PRIMARY_LIGHT.contrastText,

  DEUTERANOPIA_PRIMARY_DARK,
  DEUTERANOPIA_PRIMARY_DARK_MAIN: DEUTERANOPIA_PRIMARY_DARK.main,
  DEUTERANOPIA_PRIMARY_DARK_LIGHT: DEUTERANOPIA_PRIMARY_DARK.light,
  DEUTERANOPIA_PRIMARY_DARK_DARK: DEUTERANOPIA_PRIMARY_DARK.dark,
  DEUTERANOPIA_PRIMARY_DARK_CONTRAST: DEUTERANOPIA_PRIMARY_DARK.contrastText,

  DEUTERANOPIA_SECONDARY_LIGHT,
  DEUTERANOPIA_SECONDARY_LIGHT_MAIN: DEUTERANOPIA_SECONDARY_LIGHT.main,
  DEUTERANOPIA_SECONDARY_LIGHT_LIGHT: DEUTERANOPIA_SECONDARY_LIGHT.light,
  DEUTERANOPIA_SECONDARY_LIGHT_DARK: DEUTERANOPIA_SECONDARY_LIGHT.dark,
  DEUTERANOPIA_SECONDARY_LIGHT_CONTRAST: DEUTERANOPIA_SECONDARY_LIGHT.contrastText,

  DEUTERANOPIA_SECONDARY_DARK,
  DEUTERANOPIA_SECONDARY_DARK_MAIN: DEUTERANOPIA_SECONDARY_DARK.main,
  DEUTERANOPIA_SECONDARY_DARK_LIGHT: DEUTERANOPIA_SECONDARY_DARK.light,
  DEUTERANOPIA_SECONDARY_DARK_DARK: DEUTERANOPIA_SECONDARY_DARK.dark,
  DEUTERANOPIA_SECONDARY_DARK_CONTRAST: DEUTERANOPIA_SECONDARY_DARK.contrastText,

  // DEUTERANOMALY
  DEUTERANOMALY_PRIMARY_LIGHT,
  DEUTERANOMALY_PRIMARY_LIGHT_MAIN: DEUTERANOMALY_PRIMARY_LIGHT.main,
  DEUTERANOMALY_PRIMARY_LIGHT_LIGHT: DEUTERANOMALY_PRIMARY_LIGHT.light,
  DEUTERANOMALY_PRIMARY_LIGHT_DARK: DEUTERANOMALY_PRIMARY_LIGHT.dark,
  DEUTERANOMALY_PRIMARY_LIGHT_CONTRAST: DEUTERANOMALY_PRIMARY_LIGHT.contrastText,

  DEUTERANOMALY_PRIMARY_DARK,
  DEUTERANOMALY_PRIMARY_DARK_MAIN: DEUTERANOMALY_PRIMARY_DARK.main,
  DEUTERANOMALY_PRIMARY_DARK_LIGHT: DEUTERANOMALY_PRIMARY_DARK.light,
  DEUTERANOMALY_PRIMARY_DARK_DARK: DEUTERANOMALY_PRIMARY_DARK.dark,
  DEUTERANOMALY_PRIMARY_DARK_CONTRAST: DEUTERANOMALY_PRIMARY_DARK.contrastText,

  DEUTERANOMALY_SECONDARY_LIGHT,
  DEUTERANOMALY_SECONDARY_LIGHT_MAIN: DEUTERANOMALY_SECONDARY_LIGHT.main,
  DEUTERANOMALY_SECONDARY_LIGHT_LIGHT: DEUTERANOMALY_SECONDARY_LIGHT.light,
  DEUTERANOMALY_SECONDARY_LIGHT_DARK: DEUTERANOMALY_SECONDARY_LIGHT.dark,
  DEUTERANOMALY_SECONDARY_LIGHT_CONTRAST: DEUTERANOMALY_SECONDARY_LIGHT.contrastText,

  DEUTERANOMALY_SECONDARY_DARK,
  DEUTERANOMALY_SECONDARY_DARK_MAIN: DEUTERANOMALY_SECONDARY_DARK.main,
  DEUTERANOMALY_SECONDARY_DARK_LIGHT: DEUTERANOMALY_SECONDARY_DARK.light,
  DEUTERANOMALY_SECONDARY_DARK_DARK: DEUTERANOMALY_SECONDARY_DARK.dark,
  DEUTERANOMALY_SECONDARY_DARK_CONTRAST: DEUTERANOMALY_SECONDARY_DARK.contrastText,

  // TRITANOPIA
  TRITANOPIA_PRIMARY_LIGHT,
  TRITANOPIA_PRIMARY_LIGHT_MAIN: TRITANOPIA_PRIMARY_LIGHT.main,
  TRITANOPIA_PRIMARY_LIGHT_LIGHT: TRITANOPIA_PRIMARY_LIGHT.light,
  TRITANOPIA_PRIMARY_LIGHT_DARK: TRITANOPIA_PRIMARY_LIGHT.dark,
  TRITANOPIA_PRIMARY_LIGHT_CONTRAST: TRITANOPIA_PRIMARY_LIGHT.contrastText,

  TRITANOPIA_PRIMARY_DARK,
  TRITANOPIA_PRIMARY_DARK_MAIN: TRITANOPIA_PRIMARY_DARK.main,
  TRITANOPIA_PRIMARY_DARK_LIGHT: TRITANOPIA_PRIMARY_DARK.light,
  TRITANOPIA_PRIMARY_DARK_DARK: TRITANOPIA_PRIMARY_DARK.dark,
  TRITANOPIA_PRIMARY_DARK_CONTRAST: TRITANOPIA_PRIMARY_DARK.contrastText,

  // TRITANOPIA_SECONDARY_LIGHT
  TRITANOPIA_SECONDARY_LIGHT,
  TRITANOPIA_SECONDARY_LIGHT_MAIN: TRITANOPIA_SECONDARY_LIGHT.main,
  TRITANOPIA_SECONDARY_LIGHT_LIGHT: TRITANOPIA_SECONDARY_LIGHT.light,
  TRITANOPIA_SECONDARY_LIGHT_DARK: TRITANOPIA_SECONDARY_LIGHT.dark,
  TRITANOPIA_SECONDARY_LIGHT_CONTRAST: TRITANOPIA_SECONDARY_LIGHT.contrastText,

  // TRITANOPIA_SECONDARY_DARK
  TRITANOPIA_SECONDARY_DARK,
  TRITANOPIA_SECONDARY_DARK_MAIN: TRITANOPIA_SECONDARY_DARK.main,
  TRITANOPIA_SECONDARY_DARK_LIGHT: TRITANOPIA_SECONDARY_DARK.light,
  TRITANOPIA_SECONDARY_DARK_DARK: TRITANOPIA_SECONDARY_DARK.dark,
  TRITANOPIA_SECONDARY_DARK_CONTRAST: TRITANOPIA_SECONDARY_DARK.contrastText,

  // TRITANOMALY
  TRITANOMALY_PRIMARY_LIGHT,
  TRITANOMALY_PRIMARY_LIGHT_MAIN: TRITANOMALY_PRIMARY_LIGHT.main,
  TRITANOMALY_PRIMARY_LIGHT_LIGHT: TRITANOMALY_PRIMARY_LIGHT.light,
  TRITANOMALY_PRIMARY_LIGHT_DARK: TRITANOMALY_PRIMARY_LIGHT.dark,
  TRITANOMALY_PRIMARY_LIGHT_CONTRAST: TRITANOMALY_PRIMARY_LIGHT.contrastText,

  TRITANOMALY_PRIMARY_DARK,
  TRITANOMALY_PRIMARY_DARK_MAIN: TRITANOMALY_PRIMARY_DARK.main,
  TRITANOMALY_PRIMARY_DARK_LIGHT: TRITANOMALY_PRIMARY_DARK.light,
  TRITANOMALY_PRIMARY_DARK_DARK: TRITANOMALY_PRIMARY_DARK.dark,
  TRITANOMALY_PRIMARY_DARK_CONTRAST: TRITANOMALY_PRIMARY_DARK.contrastText,

  TRITANOMALY_SECONDARY_LIGHT,
  TRITANOMALY_SECONDARY_LIGHT_MAIN: TRITANOMALY_SECONDARY_LIGHT.main,
  TRITANOMALY_SECONDARY_LIGHT_LIGHT: TRITANOMALY_SECONDARY_LIGHT.light,
  TRITANOMALY_SECONDARY_LIGHT_DARK: TRITANOMALY_SECONDARY_LIGHT.dark,
  TRITANOMALY_SECONDARY_LIGHT_CONTRAST: TRITANOMALY_SECONDARY_LIGHT.contrastText,

  TRITANOMALY_SECONDARY_DARK,
  TRITANOMALY_SECONDARY_DARK_MAIN: TRITANOMALY_SECONDARY_DARK.main,
  TRITANOMALY_SECONDARY_DARK_LIGHT: TRITANOMALY_SECONDARY_DARK.light,
  TRITANOMALY_SECONDARY_DARK_DARK: TRITANOMALY_SECONDARY_DARK.dark,
  TRITANOMALY_SECONDARY_DARK_CONTRAST: TRITANOMALY_SECONDARY_DARK.contrastText,

  // ACHROMATOMALY
  ACHROMATOMALY_PRIMARY_LIGHT,
  ACHROMATOMALY_PRIMARY_LIGHT_MAIN: ACHROMATOMALY_PRIMARY_LIGHT.main,
  ACHROMATOMALY_PRIMARY_LIGHT_LIGHT: ACHROMATOMALY_PRIMARY_LIGHT.light,
  ACHROMATOMALY_PRIMARY_LIGHT_DARK: ACHROMATOMALY_PRIMARY_LIGHT.dark,
  ACHROMATOMALY_PRIMARY_LIGHT_CONTRAST: ACHROMATOMALY_PRIMARY_LIGHT.contrastText,

  ACHROMATOMALY_PRIMARY_DARK,
  ACHROMATOMALY_PRIMARY_DARK_MAIN: ACHROMATOMALY_PRIMARY_DARK.main,
  ACHROMATOMALY_PRIMARY_DARK_LIGHT: ACHROMATOMALY_PRIMARY_DARK.light,
  ACHROMATOMALY_PRIMARY_DARK_DARK: ACHROMATOMALY_PRIMARY_DARK.dark,
  ACHROMATOMALY_PRIMARY_DARK_CONTRAST: ACHROMATOMALY_PRIMARY_DARK.contrastText,

  ACHROMATOMALY_SECONDARY_LIGHT,
  ACHROMATOMALY_SECONDARY_LIGHT_MAIN: ACHROMATOMALY_SECONDARY_LIGHT.main,
  ACHROMATOMALY_SECONDARY_LIGHT_LIGHT: ACHROMATOMALY_SECONDARY_LIGHT.light,
  ACHROMATOMALY_SECONDARY_LIGHT_DARK: ACHROMATOMALY_SECONDARY_LIGHT.dark,
  ACHROMATOMALY_SECONDARY_LIGHT_CONTRAST: ACHROMATOMALY_SECONDARY_LIGHT.contrastText,

  ACHROMATOMALY_SECONDARY_DARK,
  ACHROMATOMALY_SECONDARY_DARK_MAIN: ACHROMATOMALY_SECONDARY_DARK.main,
  ACHROMATOMALY_SECONDARY_DARK_LIGHT: ACHROMATOMALY_SECONDARY_DARK.light,
  ACHROMATOMALY_SECONDARY_DARK_DARK: ACHROMATOMALY_SECONDARY_DARK.dark,
  ACHROMATOMALY_SECONDARY_DARK_CONTRAST: ACHROMATOMALY_SECONDARY_DARK.contrastText,

  // ACHROMATOPSIA
  ACHROMATOPSIA_PRIMARY_LIGHT,
  ACHROMATOPSIA_PRIMARY_LIGHT_MAIN: ACHROMATOPSIA_PRIMARY_LIGHT.main,
  ACHROMATOPSIA_PRIMARY_LIGHT_LIGHT: ACHROMATOPSIA_PRIMARY_LIGHT.light,
  ACHROMATOPSIA_PRIMARY_LIGHT_DARK: ACHROMATOPSIA_PRIMARY_LIGHT.dark,
  ACHROMATOPSIA_PRIMARY_LIGHT_CONTRAST: ACHROMATOPSIA_PRIMARY_LIGHT.contrastText,

  ACHROMATOPSIA_PRIMARY_DARK,
  ACHROMATOPSIA_PRIMARY_DARK_MAIN: ACHROMATOPSIA_PRIMARY_DARK.main,
  ACHROMATOPSIA_PRIMARY_DARK_LIGHT: ACHROMATOPSIA_PRIMARY_DARK.light,
  ACHROMATOPSIA_PRIMARY_DARK_DARK: ACHROMATOPSIA_PRIMARY_DARK.dark,
  ACHROMATOPSIA_PRIMARY_DARK_CONTRAST: ACHROMATOPSIA_PRIMARY_DARK.contrastText,

  ACHROMATOPSIA_SECONDARY_LIGHT,
  ACHROMATOPSIA_SECONDARY_LIGHT_MAIN: ACHROMATOPSIA_SECONDARY_LIGHT.main,
  ACHROMATOPSIA_SECONDARY_LIGHT_LIGHT: ACHROMATOPSIA_SECONDARY_LIGHT.light,
  ACHROMATOPSIA_SECONDARY_LIGHT_DARK: ACHROMATOPSIA_SECONDARY_LIGHT.dark,
  ACHROMATOPSIA_SECONDARY_LIGHT_CONTRAST: ACHROMATOPSIA_SECONDARY_LIGHT.contrastText,

  ACHROMATOPSIA_SECONDARY_DARK,
  ACHROMATOPSIA_SECONDARY_DARK_MAIN: ACHROMATOPSIA_SECONDARY_DARK.main,
  ACHROMATOPSIA_SECONDARY_DARK_LIGHT: ACHROMATOPSIA_SECONDARY_DARK.light,
  ACHROMATOPSIA_SECONDARY_DARK_DARK: ACHROMATOPSIA_SECONDARY_DARK.dark,
  ACHROMATOPSIA_SECONDARY_DARK_CONTRAST: ACHROMATOPSIA_SECONDARY_DARK.contrastText,

  // List Item Backgrounds
  DARK_LIST_ITEM_BG: '#1e1e1e',
  DARK_LIST_ITEM_SELECTED_BG: '#333333',
  LIGHT_LIST_ITEM_BG: '#f5f5f5',
  LIGHT_LIST_ITEM_SELECTED_BG: '#e0e0e0',

  // Status Backgrounds
  STATUS_BG_0: SUCCESS.bg,
  STATUS_BG_1: ERROR_1.bg,
  STATUS_BG_2: ERROR_2.bg,
  STATUS_BG_3: ERROR_3.bg,
  STATUS_BG_4: ERROR_4.bg,
  STATUS_BG_5: ERROR_5.bg,

  // Status Foregrounds
  STATUS_FG_0: SUCCESS.fg,
  STATUS_FG_1: ERROR_1.fg,
  STATUS_FG_2: ERROR_2.fg,
  STATUS_FG_3: ERROR_3.fg,
  STATUS_FG_4: ERROR_4.fg,
  STATUS_FG_5: ERROR_5.fg,

  // Full status arrays (if needed elsewhere)
  ERROR_1: ERROR_1.full,
  ERROR_2: ERROR_2.full,
  ERROR_3: ERROR_3.full,
  ERROR_4: ERROR_4.full,
  ERROR_5: ERROR_5.full,
  SUCCESS: SUCCESS.full,

  // Status soft Backgrounds
  SOFT_STATUS_BG_0: SOFT_SUCCESS.bg,
  SOFT_STATUS_BG_1: SOFT_ERROR_1.bg,
  SOFT_STATUS_BG_2: SOFT_ERROR_2.bg,
  SOFT_STATUS_BG_3: SOFT_ERROR_3.bg,
  SOFT_STATUS_BG_4: SOFT_ERROR_4.bg,
  SOFT_STATUS_BG_5: SOFT_ERROR_5.bg,

  // Status soft Foregrounds
  SOFT_STATUS_FG_0: SOFT_SUCCESS.fg,
  SOFT_STATUS_FG_1: SOFT_ERROR_1.fg,
  SOFT_STATUS_FG_2: SOFT_ERROR_2.fg,
  SOFT_STATUS_FG_3: SOFT_ERROR_3.fg,
  SOFT_STATUS_FG_4: SOFT_ERROR_4.fg,
  SOFT_STATUS_FG_5: SOFT_ERROR_5.fg,

  // Full soft status arrays (if needed elsewhere)
  SOFT_ERROR_1: SOFT_ERROR_1.full,
  SOFT_ERROR_2: SOFT_ERROR_2.full,
  SOFT_ERROR_3: SOFT_ERROR_3.full,
  SOFT_ERROR_4: SOFT_ERROR_4.full,
  SOFT_ERROR_5: SOFT_ERROR_5.full,
  SOFT_SUCCESS: SOFT_SUCCESS.full,

  // Logo Colors
  SKAO_LOGO_PRIMARY: SKAO_LOGO.primary,
  SKAO_LOGO_ACCENT: SKAO_LOGO.accent,
  SKAO_LOGO_LIGHT: SKAO_LOGO.light,

  // Telescope Colors
  SKAO_TELESCOPE_1: SKAO_TELESCOPE[1],
  SKAO_TELESCOPE_2: SKAO_TELESCOPE[2],
  SKAO_TELESCOPE_MID: SKAO_TELESCOPE.mid,
  SKAO_TELESCOPE_LOW: SKAO_TELESCOPE.low,
});
